### ISSUE TITLE
OS.Error

### ISSUE THREAD

**Issue by YINWIZHANG** [chensong1995/HybridPose#22]
HI, I am very interested in your work and trying to play with the code. However, I encounter an error when I was trying to run the train_core.py. Would you like to take a look?

```
Traceback (most recent call last):
  File "src/train_core.py", line 105, in <module>
    trainer.generate_data()
  File "/home/robot/HybridPose/trainers/coretrainer.py", line 558, in generate_data
    regressor = load_wrapper()
  File "/home/robot/HybridPose/lib/regressor/regressor.py", line 13, in load_wrapper
    regressor = CDLL('wrapper.so')
  File "/home/robot/anaconda3/envs/hybridpose/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: wrapper.so: cannot open shared object file: No such file or directory

```

**Comment by chensong1995** [comment]
Hello Yinwei,

wrapper.so is the binary for our pose regressor. Please follow README and compile the pose regressor. After that, please add the path to wrapper.so to `LD_LIBRARY_PATH` as also documented in README. 

Let me know if the problem persists.

**Comment by YINWIZHANG** [comment]
Thanks!

**Comment by LUDISO** [comment]
Hi, Hello, this error still exists when I run.
(hybridpose) dfs@dfs-Legion:~/HybridPose$ python3 src/train_core.py
number of model parameters: 12959563
Successfully loaded model from /home/dfs/saved_weights/linemod/ape/checkpoints/0.001/199
Traceback (most recent call last):
  File "src/train_core.py", line 111, in <module>
    trainer.generate_data(val_loader)
  File "./trainers/coretrainer.py", line 548, in generate_data
    regressor = load_wrapper()
  File "/home/dfs/HybridPose/lib/regressor/regressor.py", line 13, in load_wrapper
    regressor = CDLL('wrapper.so')
  File "/home/dfs/anaconda3/envs/hybridpose/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: wrapper.so: cannot open shared object file: No such file or directory

**Comment by chensong1995** [comment]
Hello LUDISO,

Thanks for your question! Please make sure to include wrapper.so in the load path:

```
$ LD_LIBRARY_PATH=lib/regressor:$LD_LIBRARY_PATH python src/train_core.py
```

I hope this helps!

**Comment by LUDISO** [comment]
Thanks!I I changed the path  
`regressor = CDLL('/home/dfs/HybridPose/lib/regressor/wrapper.so')`
