### ISSUE TITLE
关于命令行

### ISSUE THREAD

**Issue by zhuyazhi** [chensong1995/HybridPose#48]
![image](https://user-images.githubusercontent.com/48109799/96370440-61e08900-1190-11eb-826e-63c578fc37e5.png)
![image](https://user-images.githubusercontent.com/48109799/96370450-6efd7800-1190-11eb-8cd9-882b6cad8971.png)
hello~ 请问测试时parser.add_argument('--prediction_file', type=str, default='output/occlusion_linemod/test_set_ape_40.npy')中的test_set_ape_40.npy是什么作用呢，我输入默认命令行python src/evaluate.py会报以上的错误，但是不知道test_set_ape_40.npy在哪，并且在测试里有什么作用。
期待您的回复~谢谢！

**Comment by zhuyazhi** [comment]
![捕获](https://user-images.githubusercontent.com/48109799/96370645-22ff0300-1191-11eb-9387-9446573f6c34.PNG)

**Comment by zhuyazhi** [comment]
root@interactive99670:/opt/data/private/zhuyazhi/HybridPose# python src/evaluate.py
Traceback (most recent call last):
  File "src/evaluate.py", line 51, in <module>
    record = np.load(args.prediction_file, allow_pickle=True).item()
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'output/occlusion_linemod/test_set_ape_40.npy'

**Comment by zhuyazhi** [comment]
您好，请问可以给出具体一点的测试&训练的命令行吗~比如PVNet里的这种，十分感谢！
python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat

**Comment by chensong1995** [comment]
zhuyazhi 你好，

感谢你对我们工作的关注！我们在“Pre-trained weights”一段对如何使用预训练的权重进行了说明。你需要先运行`src/train_core.py`来输出npy文件，然后再运行`evaluate.py`。

希望这有帮到你！

**Comment by zhuyazhi** [comment]
![image](https://user-images.githubusercontent.com/48109799/96399327-ae63ad00-1200-11eb-82e1-e14f0c4c44fc.png)
很抱歉再次打扰您，我之前用PVNet-rendering渲染出的synthetic images如下：
![image](https://user-images.githubusercontent.com/48109799/96399501-13b79e00-1201-11eb-9f6a-51894a7cd28f.png)
我把ape的10000张render图片已经放入blender_linemod中，但是后面的ape_labels/keypoints_2d.npy不知道是什么呢？
如果我需要测试，先要运行 python src/train_core.py，但是ape_labels/keypoints_2d.npy请问怎么获得呢？
期待您的回复！

**Comment by zhuyazhi** [comment]
![image](https://user-images.githubusercontent.com/48109799/96402387-516bf500-1208-11eb-9320-c6b939a377f2.png)
很抱歉再次打扰您，我把之前PVNet-rendering渲染的10000张ape的synthetic images放入了blender_linemod中，ape文件夹中是如下的结果（通过PVNet-rendering得到）：
![image](https://user-images.githubusercontent.com/48109799/96402465-88420b00-1208-11eb-81ba-a0cdb9b70b48.png)
bu'z
按照您的建议先运行python src/train_core.py，但是关于data/blender_linemod/ape_labels/keypoints_2d.npy这个ape_labels/keypoints_2d.npy请问如何获取呢？因为按readme里面的blender_linemod组织结构，没有ape_labels这个文件夹。
期待您的回复，谢谢！

**Comment by zhuyazhi** [comment]
![image](https://user-images.githubusercontent.com/48109799/96402587-e40c9400-1208-11eb-832a-cea6dde1afd2.png)
上面报错的截图~

**Comment by chensong1995** [comment]
zhuyazhi 你好，

可以使用 data/label.py 以及 data/label_fuse.py 来创建标注哦

**Comment by zhuyazhi** [comment]
好的，谢谢您的回复~
您使用的synthetic Images也是如同这样的吗（0.jpg, 0_depth.png, 0_RT.pkl）
![image](https://user-images.githubusercontent.com/48109799/96406906-ea077280-1212-11eb-96ca-51fdacb38a28.png)
另外，据我所知~PVNet是13个物体共用10000张fuse合成图片，请问fuse_linemod是怎么把他们分开成13个物体对应的fuse images呢？
![image](https://user-images.githubusercontent.com/48109799/96407079-2c30b400-1213-11eb-8ebf-924e803d0ae2.png)

**Comment by zhuyazhi** [comment]
Dear author:
我改了部分label.py中的路径，运行了python label.py，结果生成了ape_labels/keypoints_2d.npy，然后我把ape_labels/keypoints_2d.npy放入data/blender_linemod文件夹中，如下
![image](https://user-images.githubusercontent.com/48109799/96412969-7b7be200-121d-11eb-964b-457a24147bbc.png)
1. 上图中的ape就是通过pvnet-rendering渲染的图片（0.jpg, 0_depth.png, 0_RT.pkl），请问目前我blender_linemod数据集排布格式对吗？
2. 据我所知~PVNet是13个物体共用10000张fuse合成图片，所以只有一个fuse文件夹，没有分成（ape,benchvise......)。请问您的fuse_linemod中也是13个物体共用10000张fuse合成图片吗，复制13份分别命名为13个物体的名字吗？如果不是的话，请问fuse_linemod是怎么把他们分开成13个物体对应的fuse images呢？

**Comment by zhuyazhi** [comment]
![image](https://user-images.githubusercontent.com/48109799/96416251-5b9aed00-1222-11eb-983d-f8a21d4c7ed6.png)
这是我改的两个路径，ape_labels最后生成了错误的结果，只有keypoints_2d.npy并且里面没有内容。
![image](https://user-images.githubusercontent.com/48109799/96416327-779e8e80-1222-11eb-96cc-392ffc520f90.png)
您能给我一些建议吗？

**Comment by chensong1995** [comment]
zhuyazhi 你好，

抱歉，之前README对数据目录结构的说明存在一些问题。我刚刚更新了一下，你可以再试试看～

**Comment by zhuyazhi** [comment]
谢谢您的细心更改，我目前有两个疑惑：
1.因为我想测试，您的建议是我先运行先运行python src/train_core.py（需要等训练完成来输出npy文件），我的疑惑是这不代表我开始正式的训练了吗？
2.我将之前PVNet的数据集放入HybridPose/data/pvnet_linemod中，
![image](https://user-images.githubusercontent.com/48109799/96526256-ab73c580-12af-11eb-876f-6b9213c244fa.png)
上图我在代码中改的两个路径，ape_labels最后生成了错误的结果，只有keypoints_2d.npy一个.npy文件并且里面没有内容。
![image](https://user-images.githubusercontent.com/48109799/96526323-cc3c1b00-12af-11eb-8bd7-7d5b50f20003.png)
我看代码中正常情况是还会有{}_labels/cor{}.npy；您对我的输出错误有什么建议吗？比如我以上的路径不应该那么改~
期待您的回复！（同时也为打扰您感到抱歉）

**Comment by chensong1995** [comment]
zhuyazhi 你好，

1. 如果提供给 train_core.py 预训练好的权重，代码会判断保存权重时的纪元 (epoch) 是不是超过训练总纪元数 (默认为200) 。如果超过的话，将会直接跳转到测试的逻辑。

2. 如果有需要的话，可以发邮件给我，我们约个时间远程协助看一下。

希望这有帮到你

**Comment by LUDISO** [comment]
我使用了synthetic data from PVNet，但我使用他们的代码没能生成blender rendering和fuse data，运行python3 run.py --type rendering和python3 run.py --type fuse显示如下
`(hybridpose) dfs@dfs-Legion:~/pvnet-rendering$ python3 run.py --type rendering
found bundled python: /home/dfs/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python
Read blend: /home/dfs/pvnet-rendering/data/blank.blend

Successfully imported '/home/dfs/pvnet-rendering/data/LINEMOD/cat/cat.ply' in 1.169 sec
cost 1.2309236526489258 s

Blender quit`

**Comment by chensong1995** [comment]
LUDISO 你好，

根据你的情况描述我暂时不能确定问题出在哪里，你可以发个邮件给我，我们约个时间远程协助一起看一下。

希望这有帮到你！
