### ISSUE TITLE
I'll ask you questions about some errors!

### ISSUE THREAD

**Issue by choikhss** [chensong1995/HybridPose#58]
HI! I have several questions, so i will ask by number.!!

-1- 
Traceback (most recent call last):
  File "src/train_core.py", line 124, in <module>
    trainer.train(epoch)
  File "./trainers/coretrainer.py", line 36, in train
    for i_batch, batch in enumerate(self.train_loader):
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.

-2- 
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/PycharmProjects/hybridpose/HybridPose/lib/datasets/concat.py", line 48, in __getitem__
    return self.datasets[dataset_idx][sample_idx, height, width]
  File "/home/user/PycharmProjects/hybridpose/HybridPose/lib/datasets/blender_linemod.py", line 204, in __getitem__
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.7) ../modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

-3- 
When i run 'train_core', <model = nn.DataParallel(model).cuda()> code is too slow :(
It takes about 15 minutes..or more .. 

--
 All of these Problems occur When running train_core code !

I'll wait for your reply!
Thank you!

**Comment by chensong1995** [comment]
Hello choikhss,

Thanks for the interest in our work! Please make sure you have correctly prepared the datasets according to README.

I hope this helps.
