### ISSUE TITLE
error downloading occlusion linemod using your script

### ISSUE THREAD

**Issue by monajalal** [chensong1995/HybridPose#78]
I get this error:
```
(hybridpose) mona@mona-ThinkStation-P7:~/HybridPose$ python data/download_occlusion.py
Traceback (most recent call last):
  File "/home/mona/HybridPose/data/download_occlusion.py", line 18, in <module>
    download_and_unzip()
  File "/home/mona/HybridPose/data/download_occlusion.py", line 11, in download_and_unzip
    urllib.request.urlretrieve(url, target_file)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 
```

I don't get an error for `(hybridpose) mona@mona-ThinkStation-P7:~/HybridPose$ python data/download_linemod.py`

**Comment by monajalal** [comment]
When I browse to 
https://datashare.tu-dresden.de/index.php/s/a65ec05fedd4890ae8ced82dfcf92ad8/download

I get this error:
![Screenshot from 2023-10-16 16-06-31](https://github.com/chensong1995/HybridPose/assets/1892917/b4e141fa-7d2a-4845-b14b-8949a06a7add)

![image](https://github.com/chensong1995/HybridPose/assets/1892917/e2daca77-ff15-4ef2-8e26-a87ea56cf24d)


Do you have a fix for this?

**Comment by chensong1995** [comment]
Hi Mona,

Thanks for your question! Unfortunately, I do not have a fix for this. It looks to me that the authors of the dataset have deactivated the link in favor of a "reworked version of the dataset as part of the [BOP Challenge](https://bop.felk.cvut.cz/datasets/)", and "The reworked version contains all data (images, poses, 3D models of objects) and some annotation errors have been corrected".  You are welcome to go ahead and download the reworked version. However, keep in mind that you may need to manually change a few lines in the code to address the difference in data formats.

I hope this helps! Let me know if you have further concerns.
